### ISSUE TITLE
Global Statistics reference for unlogged user

### ISSUE THREAD

**Issue by OlyaOlga** [BaranovMykola/RoadRulesTestingService#63]
When no user is logged this link is shown.
![image](https://user-images.githubusercontent.com/23266277/39537510-86eeefd4-4e42-11e8-9069-bd79f8abab8f.png)
When user clicks on it he receives the following:
![image](https://user-images.githubusercontent.com/23266277/39537657-ec6c7854-4e42-11e8-9d45-518fe974d7e4.png)
This should be fixed.

**Comment by BaranovMykola** [comment]
Done
